#ifndef __MAIN_H_
#define __MAIN_H_

#define TILEMAP_TILE_SIZE 32

#define TILEMAP_WIDTH       40
#define TILEMAP_HEIGHT      200

#define TILEMAP_DRAW_WIDTH  10
#define TILEMAP_DRAW_HEIGHT 7

#define TILEMAP_MAX_X (TILEMAP_WIDTH * TILEMAP_TILE_SIZE)
#define TILEMAP_MAX_Y (TILEMAP_HEIGHT * TILEMAP_TILE_SIZE)

#endif
