#ifndef MINIMAP_H
#define MINIMAP_H

#define MINIMAP_COLS 20
#define MINIMAP_ROWS 14
#define MINIMAP_TILE_SIZE 5
#define MINIMAP_X 3 
#define MINIMAP_Y 3
#define MINIMAP_WIDTH (MINIMAP_COLS * MINIMAP_TILE_SIZE)
#define MINIMAP_HEIGHT (MINIMAP_ROWS * MINIMAP_TILE_SIZE)

void minimap();

#endif
