// Converted using ConvPNG
// This file contains all the graphics sources for easier inclusion in a project
#ifndef __dungeon_gfx__
#define __dungeon_gfx__
#include <stdint.h>

#define dungeon_gfx_transparent_color_index 0

#define player_naked_down_width 32
#define player_naked_down_height 32
#define player_naked_down_size 1026
extern uint8_t player_naked_down_data[1026];
#define player_naked_down ((gfx_sprite_t*)player_naked_down_data)
#define leather_helmet_down_width 32
#define leather_helmet_down_height 32
#define leather_helmet_down_size 1026
extern uint8_t leather_helmet_down_data[1026];
#define leather_helmet_down ((gfx_sprite_t*)leather_helmet_down_data)
#define chain_helmet_down_width 32
#define chain_helmet_down_height 32
#define chain_helmet_down_size 1026
extern uint8_t chain_helmet_down_data[1026];
#define chain_helmet_down ((gfx_sprite_t*)chain_helmet_down_data)
#define steel_helmet_down_width 32
#define steel_helmet_down_height 32
#define steel_helmet_down_size 1026
extern uint8_t steel_helmet_down_data[1026];
#define steel_helmet_down ((gfx_sprite_t*)steel_helmet_down_data)
#define dragon_helmet_down_width 32
#define dragon_helmet_down_height 32
#define dragon_helmet_down_size 1026
extern uint8_t dragon_helmet_down_data[1026];
#define dragon_helmet_down ((gfx_sprite_t*)dragon_helmet_down_data)
#define leather_chestplate_down_width 32
#define leather_chestplate_down_height 32
#define leather_chestplate_down_size 1026
extern uint8_t leather_chestplate_down_data[1026];
#define leather_chestplate_down ((gfx_sprite_t*)leather_chestplate_down_data)
#define chain_chestplate_down_width 32
#define chain_chestplate_down_height 32
#define chain_chestplate_down_size 1026
extern uint8_t chain_chestplate_down_data[1026];
#define chain_chestplate_down ((gfx_sprite_t*)chain_chestplate_down_data)
#define steel_chestplate_down_width 32
#define steel_chestplate_down_height 32
#define steel_chestplate_down_size 1026
extern uint8_t steel_chestplate_down_data[1026];
#define steel_chestplate_down ((gfx_sprite_t*)steel_chestplate_down_data)
#define dragon_chestplate_down_width 32
#define dragon_chestplate_down_height 32
#define dragon_chestplate_down_size 1026
extern uint8_t dragon_chestplate_down_data[1026];
#define dragon_chestplate_down ((gfx_sprite_t*)dragon_chestplate_down_data)
#define leather_boots_down_width 32
#define leather_boots_down_height 32
#define leather_boots_down_size 1026
extern uint8_t leather_boots_down_data[1026];
#define leather_boots_down ((gfx_sprite_t*)leather_boots_down_data)
#define chain_boots_down_width 32
#define chain_boots_down_height 32
#define chain_boots_down_size 1026
extern uint8_t chain_boots_down_data[1026];
#define chain_boots_down ((gfx_sprite_t*)chain_boots_down_data)
#define steel_boots_down_width 32
#define steel_boots_down_height 32
#define steel_boots_down_size 1026
extern uint8_t steel_boots_down_data[1026];
#define steel_boots_down ((gfx_sprite_t*)steel_boots_down_data)
#define dragon_boots_down_width 32
#define dragon_boots_down_height 32
#define dragon_boots_down_size 1026
extern uint8_t dragon_boots_down_data[1026];
#define dragon_boots_down ((gfx_sprite_t*)dragon_boots_down_data)
#define club_width 32
#define club_height 32
#define club_size 1026
extern uint8_t club_data[1026];
#define club ((gfx_sprite_t*)club_data)
#define iron_sword_width 32
#define iron_sword_height 32
#define iron_sword_size 1026
extern uint8_t iron_sword_data[1026];
#define iron_sword ((gfx_sprite_t*)iron_sword_data)
#define steel_sword_width 32
#define steel_sword_height 32
#define steel_sword_size 1026
extern uint8_t steel_sword_data[1026];
#define steel_sword ((gfx_sprite_t*)steel_sword_data)
#define dragon_sword_width 32
#define dragon_sword_height 32
#define dragon_sword_size 1026
extern uint8_t dragon_sword_data[1026];
#define dragon_sword ((gfx_sprite_t*)dragon_sword_data)
#define optionsmenu_width 171
#define optionsmenu_height 90
#define optionsmenu_size 15392
extern uint8_t optionsmenu_data[15392];
#define optionsmenu ((gfx_sprite_t*)optionsmenu_data)
#define editmenunumbers_width 24
#define editmenunumbers_height 200
#define editmenunumbers_size 4802
extern uint8_t editmenunumbers_data[4802];
#define editmenunumbers ((gfx_sprite_t*)editmenunumbers_data)
#define mainmenulogo_width 253
#define mainmenulogo_height 90
#define mainmenulogo_size 22772
extern uint8_t mainmenulogo_data[22772];
#define mainmenulogo ((gfx_sprite_t*)mainmenulogo_data)
#define menuwords_width 100
#define menuwords_height 50
#define menuwords_size 5002
extern uint8_t menuwords_data[5002];
#define menuwords ((gfx_sprite_t*)menuwords_data)
#define sizeof_dungeon_gfx_pal 512
extern uint16_t dungeon_gfx_pal[256];

#endif
