// convpng v7.1
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __dungeon__
#define __dungeon__
#include <stdint.h>

#include <stdbool.h>

#define dungeon_num 88

extern uint8_t *dungeon[88];
#define player_naked_down_width 32
#define player_naked_down_height 32
#define player_naked_down ((gfx_sprite_t*)dungeon[0])
#define player_naked_left_width 32
#define player_naked_left_height 32
#define player_naked_left ((gfx_sprite_t*)dungeon[1])
#define player_naked_right_width 32
#define player_naked_right_height 32
#define player_naked_right ((gfx_sprite_t*)dungeon[2])
#define player_naked_up_width 32
#define player_naked_up_height 32
#define player_naked_up ((gfx_sprite_t*)dungeon[3])
#define leather_boots_down_width 32
#define leather_boots_down_height 5
#define leather_boots_down ((gfx_sprite_t*)dungeon[4])
#define leather_boots_left_width 32
#define leather_boots_left_height 5
#define leather_boots_left ((gfx_sprite_t*)dungeon[5])
#define leather_boots_up_width 32
#define leather_boots_up_height 5
#define leather_boots_up ((gfx_sprite_t*)dungeon[6])
#define leather_chestplate_down_width 32
#define leather_chestplate_down_height 32
#define leather_chestplate_down ((gfx_sprite_t*)dungeon[7])
#define leather_chestplate_left_width 32
#define leather_chestplate_left_height 32
#define leather_chestplate_left ((gfx_sprite_t*)dungeon[8])
#define leather_chestplate_up_width 32
#define leather_chestplate_up_height 32
#define leather_chestplate_up ((gfx_sprite_t*)dungeon[9])
#define leather_helmet_down_width 32
#define leather_helmet_down_height 11
#define leather_helmet_down ((gfx_sprite_t*)dungeon[10])
#define leather_helmet_left_width 32
#define leather_helmet_left_height 11
#define leather_helmet_left ((gfx_sprite_t*)dungeon[11])
#define leather_helmet_up_width 32
#define leather_helmet_up_height 11
#define leather_helmet_up ((gfx_sprite_t*)dungeon[12])
#define chain_boots_down_width 32
#define chain_boots_down_height 5
#define chain_boots_down ((gfx_sprite_t*)dungeon[13])
#define chain_boots_left_width 32
#define chain_boots_left_height 5
#define chain_boots_left ((gfx_sprite_t*)dungeon[14])
#define chain_boots_up_width 32
#define chain_boots_up_height 5
#define chain_boots_up ((gfx_sprite_t*)dungeon[15])
#define chain_chestplate_down_width 32
#define chain_chestplate_down_height 32
#define chain_chestplate_down ((gfx_sprite_t*)dungeon[16])
#define chain_chestplate_left_width 32
#define chain_chestplate_left_height 32
#define chain_chestplate_left ((gfx_sprite_t*)dungeon[17])
#define chain_chestplate_up_width 32
#define chain_chestplate_up_height 32
#define chain_chestplate_up ((gfx_sprite_t*)dungeon[18])
#define chain_helmet_down_width 32
#define chain_helmet_down_height 16
#define chain_helmet_down ((gfx_sprite_t*)dungeon[19])
#define chain_helmet_left_width 32
#define chain_helmet_left_height 16
#define chain_helmet_left ((gfx_sprite_t*)dungeon[20])
#define chain_helmet_up_width 32
#define chain_helmet_up_height 16
#define chain_helmet_up ((gfx_sprite_t*)dungeon[21])
#define steel_boots_down_width 32
#define steel_boots_down_height 5
#define steel_boots_down ((gfx_sprite_t*)dungeon[22])
#define steel_boots_left_width 32
#define steel_boots_left_height 5
#define steel_boots_left ((gfx_sprite_t*)dungeon[23])
#define steel_boots_up_width 32
#define steel_boots_up_height 5
#define steel_boots_up ((gfx_sprite_t*)dungeon[24])
#define steel_chestplate_down_width 32
#define steel_chestplate_down_height 32
#define steel_chestplate_down ((gfx_sprite_t*)dungeon[25])
#define steel_chestplate_left_width 32
#define steel_chestplate_left_height 32
#define steel_chestplate_left ((gfx_sprite_t*)dungeon[26])
#define steel_chestplate_up_width 32
#define steel_chestplate_up_height 32
#define steel_chestplate_up ((gfx_sprite_t*)dungeon[27])
#define steel_helmet_down_width 32
#define steel_helmet_down_height 17
#define steel_helmet_down ((gfx_sprite_t*)dungeon[28])
#define steel_helmet_left_width 32
#define steel_helmet_left_height 17
#define steel_helmet_left ((gfx_sprite_t*)dungeon[29])
#define steel_helmet_up_width 32
#define steel_helmet_up_height 17
#define steel_helmet_up ((gfx_sprite_t*)dungeon[30])
#define steel_sword_width 32
#define steel_sword_height 32
#define steel_sword ((gfx_sprite_t*)dungeon[31])
#define steel_sword_inv_width 16
#define steel_sword_inv_height 16
#define steel_sword_inv ((gfx_sprite_t*)dungeon[32])
#define dragon_boots_down_width 32
#define dragon_boots_down_height 5
#define dragon_boots_down ((gfx_sprite_t*)dungeon[33])
#define dragon_boots_left_width 32
#define dragon_boots_left_height 5
#define dragon_boots_left ((gfx_sprite_t*)dungeon[34])
#define dragon_boots_up_width 32
#define dragon_boots_up_height 5
#define dragon_boots_up ((gfx_sprite_t*)dungeon[35])
#define dragon_chestplate_down_width 32
#define dragon_chestplate_down_height 32
#define dragon_chestplate_down ((gfx_sprite_t*)dungeon[36])
#define dragon_chestplate_left_width 32
#define dragon_chestplate_left_height 32
#define dragon_chestplate_left ((gfx_sprite_t*)dungeon[37])
#define dragon_chestplate_up_width 32
#define dragon_chestplate_up_height 32
#define dragon_chestplate_up ((gfx_sprite_t*)dungeon[38])
#define dragon_helmet_down_width 32
#define dragon_helmet_down_height 16
#define dragon_helmet_down ((gfx_sprite_t*)dungeon[39])
#define dragon_helmet_left_width 32
#define dragon_helmet_left_height 16
#define dragon_helmet_left ((gfx_sprite_t*)dungeon[40])
#define dragon_helmet_up_width 32
#define dragon_helmet_up_height 16
#define dragon_helmet_up ((gfx_sprite_t*)dungeon[41])
#define dragon_sword_width 32
#define dragon_sword_height 32
#define dragon_sword ((gfx_sprite_t*)dungeon[42])
#define dragon_sword_inv_width 16
#define dragon_sword_inv_height 16
#define dragon_sword_inv ((gfx_sprite_t*)dungeon[43])
#define fist_width 32
#define fist_height 32
#define fist ((gfx_sprite_t*)dungeon[44])
#define club_width 32
#define club_height 32
#define club ((gfx_sprite_t*)dungeon[45])
#define club_inv_width 16
#define club_inv_height 16
#define club_inv ((gfx_sprite_t*)dungeon[46])
#define iron_sword_width 32
#define iron_sword_height 32
#define iron_sword ((gfx_sprite_t*)dungeon[47])
#define iron_sword_inv_width 16
#define iron_sword_inv_height 16
#define iron_sword_inv ((gfx_sprite_t*)dungeon[48])
#define no_item_width 32
#define no_item_height 32
#define no_item ((gfx_sprite_t*)dungeon[49])
#define bow_basic_width 32
#define bow_basic_height 7
#define bow_basic ((gfx_sprite_t*)dungeon[50])
#define bow_basic_inv_width 16
#define bow_basic_inv_height 16
#define bow_basic_inv ((gfx_sprite_t*)dungeon[51])
#define bow_compound_width 32
#define bow_compound_height 7
#define bow_compound ((gfx_sprite_t*)dungeon[52])
#define bow_compound_inv_width 16
#define bow_compound_inv_height 16
#define bow_compound_inv ((gfx_sprite_t*)dungeon[53])
#define bow_dragon_width 32
#define bow_dragon_height 7
#define bow_dragon ((gfx_sprite_t*)dungeon[54])
#define bow_dragon_inv_width 16
#define bow_dragon_inv_height 16
#define bow_dragon_inv ((gfx_sprite_t*)dungeon[55])
#define bow_recurve_width 32
#define bow_recurve_height 7
#define bow_recurve ((gfx_sprite_t*)dungeon[56])
#define bow_recurve_inv_width 16
#define bow_recurve_inv_height 16
#define bow_recurve_inv ((gfx_sprite_t*)dungeon[57])
#define potion_green_width 16
#define potion_green_height 16
#define potion_green ((gfx_sprite_t*)dungeon[58])
#define potion_purple_width 16
#define potion_purple_height 16
#define potion_purple ((gfx_sprite_t*)dungeon[59])
#define potion_red_width 16
#define potion_red_height 16
#define potion_red ((gfx_sprite_t*)dungeon[60])
#define tombstone_width 32
#define tombstone_height 32
#define tombstone ((gfx_sprite_t*)dungeon[61])
#define pot_width 32
#define pot_height 32
#define pot ((gfx_sprite_t*)dungeon[62])
#define health10_width 61
#define health10_height 14
#define health10 ((gfx_sprite_t*)dungeon[63])
#define health_empty_width 61
#define health_empty_height 14
#define health_empty ((gfx_sprite_t*)dungeon[64])
#define money1_width 32
#define money1_height 32
#define money1 ((gfx_sprite_t*)dungeon[65])
#define money10_width 32
#define money10_height 32
#define money10 ((gfx_sprite_t*)dungeon[66])
#define money100_width 32
#define money100_height 32
#define money100 ((gfx_sprite_t*)dungeon[67])
#define money20_width 32
#define money20_height 32
#define money20 ((gfx_sprite_t*)dungeon[68])
#define money5_width 32
#define money5_height 32
#define money5 ((gfx_sprite_t*)dungeon[69])
#define attack_blue_width 32
#define attack_blue_height 32
#define attack_blue ((gfx_sprite_t*)dungeon[70])
#define attack_green_width 32
#define attack_green_height 32
#define attack_green ((gfx_sprite_t*)dungeon[71])
#define attack_red_width 32
#define attack_red_height 32
#define attack_red ((gfx_sprite_t*)dungeon[72])
#define arrow_width 32
#define arrow_height 5
#define arrow ((gfx_sprite_t*)dungeon[73])
#define arrow_hitwall_width 5
#define arrow_hitwall_height 5
#define arrow_hitwall ((gfx_sprite_t*)dungeon[74])
#define slime_blue_width 32
#define slime_blue_height 32
#define slime_blue ((gfx_sprite_t*)dungeon[75])
#define slime_green_width 32
#define slime_green_height 32
#define slime_green ((gfx_sprite_t*)dungeon[76])
#define slime_red_width 32
#define slime_red_height 32
#define slime_red ((gfx_sprite_t*)dungeon[77])
#define bokoblin_dark_width 32
#define bokoblin_dark_height 32
#define bokoblin_dark ((gfx_sprite_t*)dungeon[78])
#define bokoblin_light_width 32
#define bokoblin_light_height 32
#define bokoblin_light ((gfx_sprite_t*)dungeon[79])
#define relic1_width 32
#define relic1_height 32
#define relic1 ((gfx_sprite_t*)dungeon[80])
#define player_arrow_down_width 5
#define player_arrow_down_height 5
#define player_arrow_down ((gfx_sprite_t*)dungeon[81])
#define player_arrow_left_width 5
#define player_arrow_left_height 5
#define player_arrow_left ((gfx_sprite_t*)dungeon[82])
#define player_arrow_right_width 5
#define player_arrow_right_height 5
#define player_arrow_right ((gfx_sprite_t*)dungeon[83])
#define player_arrow_up_width 5
#define player_arrow_up_height 5
#define player_arrow_up ((gfx_sprite_t*)dungeon[84])
#define menuarrowL_width 8
#define menuarrowL_height 8
#define menuarrowL ((gfx_sprite_t*)dungeon[85])
#define menuarrowR_width 8
#define menuarrowR_height 8
#define menuarrowR ((gfx_sprite_t*)dungeon[86])
#define menuskull_width 8
#define menuskull_height 8
#define menuskull ((gfx_sprite_t*)dungeon[87])
bool dungeon_init(void);

#endif
